import type { SelectOption } from '../../framework/fieldMeta'
import { mulberry32 } from '../../framework/rng'

// The bundled picture set: individual pixel-art SPRITES — a sword, a potion, a
// little character — each one its own picture for the turrets to dismantle.
// Generated by scripts/slice-sprites.mjs from CC0 sprite sheets and committed as
// ordinary code, so the schema's options and the rotation are typed and testable
// without touching the filesystem or the network.
//
// Why sprites rather than scenes: a sprite is already quantized to a tiny flat
// palette, and its transparent surround becomes empty space the beams cross, so
// the picture reads as a single object floating in the frame and coming apart —
// rather than a landscape eroding. It also means `cellSize` stops being a detail
// knob (a 16x16 sprite has no more detail to reveal) and becomes purely a
// how-long-does-this-take knob.

export interface Picture {
  slug: string
  title: string
  author: string
  /** The human page whose licence statement was actually read. */
  sourceUrl: string
  license: string
}

export const PICTURES: Picture[] = [
  { slug: 'silver-sword', title: "Silver Sword",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'golden-sword', title: "Golden Sword",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'blue-potion', title: "Blue Potion",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'red-flask', title: "Red Flask",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'green-potion', title: "Green Potion",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'jewelled-crown', title: "Jewelled Crown",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'purple-crown', title: "Purple Crown",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'crystal-wand', title: "Crystal Wand",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'scroll', title: "Scroll",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'wooden-staff', title: "Wooden Staff",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'scimitar', title: "Scimitar",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'cauldron', title: "Cauldron",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'axe', title: "Axe",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'helm', title: "Helm",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'treasure-chest', title: "Treasure Chest",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'red-gem', title: "Red Gem",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'purple-gem', title: "Purple Gem",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'green-gem', title: "Green Gem",
    author: "jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'red-top', title: "Red Top",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'red-tunic', title: "Red Tunic",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'orange-dress', title: "Orange Dress",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'brown-braid', title: "Brown Braid",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'olive-coat', title: "Olive Coat",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'green-top', title: "Green Top",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'teal-hair', title: "Teal Hair",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'purple-dress', title: "Purple Dress",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
]

export const SHUFFLE_ALL = 'shuffle'

export function hasPicture(slug: string): boolean {
  return PICTURES.some((p) => p.slug === slug)
}

/** The slugs a selection plays, in the order it plays them.
 *
 *  Seeded, so a pinned seed reproduces the whole sequence — consistent with the
 *  seed field's documented job ("fixes the picture sequence") rather than an
 *  extension of it. An unknown selection degrades to everything rather than to
 *  nothing, so a link naming a sprite that has since been removed still plays. */
export function rotationOrder(selection: string, seed: number): string[] {
  if (hasPicture(selection)) return [selection]
  return shuffle(PICTURES.map((p) => p.slug), seed)
}

/** Fisher-Yates. A sort with a random comparator is NOT a uniform shuffle and is
 *  unstable across engines, either of which would break the determinism the seed
 *  contract promises. */
function shuffle(slugs: string[], seed: number): string[] {
  const out = slugs.slice()
  const rand = mulberry32(seed)
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1))
    ;[out[i], out[j]] = [out[j], out[i]]
  }
  return out
}

export const PICTURE_OPTIONS: SelectOption[] = [
  { value: SHUFFLE_ALL, label: 'Shuffle all' },
  ...PICTURES.map((p) => ({ value: p.slug, label: p.title })),
]
