import type { SelectOption } from '../../framework/fieldMeta'
import { mulberry32 } from '../../framework/rng'

// The bundled picture set: individual pixel-art SPRITES — a sword, a potion, a
// little character — each one its own picture for the turrets to dismantle.
// Generated by scripts/slice-sprites.mjs from CC0 sprite sheets and committed as
// ordinary code, so the schema's options and the rotation are typed and testable
// without touching the filesystem or the network.
//
// Why sprites rather than scenes: a sprite is already quantized to a tiny flat
// palette, and its transparent surround becomes empty space the beams cross, so
// the picture reads as a single object floating in the frame and coming apart —
// rather than a landscape eroding. It also means `cellSize` stops being a detail
// knob (a 16x16 sprite has no more detail to reveal) and becomes purely a
// how-long-does-this-take knob.

export interface Picture {
  slug: string
  title: string
  author: string
  /** The human page whose licence statement was actually read. */
  sourceUrl: string
  license: string
}

export const PICTURES: Picture[] = [
  { slug: 'silver-sword', title: "Silver Sword",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'golden-sword', title: "Golden Sword",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'blue-potion', title: "Blue Potion",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'red-flask', title: "Red Flask",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'green-potion', title: "Green Potion",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'jewelled-crown', title: "Jewelled Crown",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'purple-crown', title: "Purple Crown",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'crystal-wand', title: "Crystal Wand",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'scroll', title: "Scroll",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'wooden-staff', title: "Wooden Staff",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'scimitar', title: "Scimitar",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'cauldron', title: "Cauldron",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'axe', title: "Axe",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'helm', title: "Helm",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'treasure-chest', title: "Treasure Chest",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'red-gem', title: "Red Gem",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'purple-gem', title: "Purple Gem",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'green-gem', title: "Green Gem",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/16x16-rpg-items', license: 'CC0 1.0' },
  { slug: 'red-top', title: "Red Top",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'red-tunic', title: "Red Tunic",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'orange-dress', title: "Orange Dress",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'brown-braid', title: "Brown Braid",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'olive-coat', title: "Olive Coat",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'green-top', title: "Green Top",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'teal-hair', title: "Teal Hair",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'purple-dress', title: "Purple Dress",
    author: "fleurman", sourceUrl: 'https://opengameart.org/content/tiny-characters-set', license: 'CC0 1.0' },
  { slug: 'toadstool', title: "Toadstool",
    author: "Clint Bellanger", sourceUrl: 'https://opengameart.org/content/tiny-creatures', license: 'CC0 1.0' },
  { slug: 'blue-dragon', title: "Blue Dragon",
    author: "Clint Bellanger", sourceUrl: 'https://opengameart.org/content/tiny-creatures', license: 'CC0 1.0' },
  { slug: 'red-dragon', title: "Red Dragon",
    author: "Clint Bellanger", sourceUrl: 'https://opengameart.org/content/tiny-creatures', license: 'CC0 1.0' },
  { slug: 'flame', title: "Flame",
    author: "Clint Bellanger", sourceUrl: 'https://opengameart.org/content/tiny-creatures', license: 'CC0 1.0' },
  { slug: 'purple-wizard', title: "Purple Wizard",
    author: "Clint Bellanger", sourceUrl: 'https://opengameart.org/content/tiny-creatures', license: 'CC0 1.0' },
  { slug: 'owl', title: "Owl",
    author: "Clint Bellanger", sourceUrl: 'https://opengameart.org/content/tiny-creatures', license: 'CC0 1.0' },
  { slug: 'zebra', title: "Zebra",
    author: "Clint Bellanger", sourceUrl: 'https://opengameart.org/content/tiny-creatures', license: 'CC0 1.0' },
  { slug: 'lion', title: "Lion",
    author: "Clint Bellanger", sourceUrl: 'https://opengameart.org/content/tiny-creatures', license: 'CC0 1.0' },
  { slug: 'tiger', title: "Tiger",
    author: "Clint Bellanger", sourceUrl: 'https://opengameart.org/content/tiny-creatures', license: 'CC0 1.0' },
  { slug: 'elephant', title: "Elephant",
    author: "Clint Bellanger", sourceUrl: 'https://opengameart.org/content/tiny-creatures', license: 'CC0 1.0' },
  { slug: 'giraffe', title: "Giraffe",
    author: "Clint Bellanger", sourceUrl: 'https://opengameart.org/content/tiny-creatures', license: 'CC0 1.0' },
  { slug: 'fox', title: "Fox",
    author: "Clint Bellanger", sourceUrl: 'https://opengameart.org/content/tiny-creatures', license: 'CC0 1.0' },
  { slug: 'red-mushroom', title: "Red Mushroom",
    author: "AndHeGames", sourceUrl: 'https://opengameart.org/content/assorted-32x32-creatures', license: 'CC0 1.0' },
  { slug: 'purple-blob', title: "Purple Blob",
    author: "AndHeGames", sourceUrl: 'https://opengameart.org/content/assorted-32x32-creatures', license: 'CC0 1.0' },
  { slug: 'orb-walker', title: "Orb Walker",
    author: "AndHeGames", sourceUrl: 'https://opengameart.org/content/assorted-32x32-creatures', license: 'CC0 1.0' },
  { slug: 'green-frog', title: "Green Frog",
    author: "AndHeGames", sourceUrl: 'https://opengameart.org/content/assorted-32x32-creatures', license: 'CC0 1.0' },
  { slug: 'blue-beetle', title: "Blue Beetle",
    author: "AndHeGames", sourceUrl: 'https://opengameart.org/content/assorted-32x32-creatures', license: 'CC0 1.0' },
  { slug: 'green-cube', title: "Green Cube",
    author: "AndHeGames", sourceUrl: 'https://opengameart.org/content/assorted-32x32-creatures', license: 'CC0 1.0' },
  { slug: 'red-imp', title: "Red Imp",
    author: "AndHeGames", sourceUrl: 'https://opengameart.org/content/assorted-32x32-creatures', license: 'CC0 1.0' },
  { slug: 'blue-ghost', title: "Blue Ghost",
    author: "AndHeGames", sourceUrl: 'https://opengameart.org/content/assorted-32x32-creatures', license: 'CC0 1.0' },
  { slug: 'pink-squid', title: "Pink Squid",
    author: "AndHeGames", sourceUrl: 'https://opengameart.org/content/assorted-32x32-creatures', license: 'CC0 1.0' },
  { slug: 'blue-slime', title: "Blue Slime",
    author: "AndHeGames", sourceUrl: 'https://opengameart.org/content/assorted-32x32-creatures', license: 'CC0 1.0' },
  { slug: 'pink-blob', title: "Pink Blob",
    author: "GrafxKid", sourceUrl: 'https://opengameart.org/content/various-creatures', license: 'CC0 1.0' },
  { slug: 'orange-snail', title: "Orange Snail",
    author: "GrafxKid", sourceUrl: 'https://opengameart.org/content/various-creatures', license: 'CC0 1.0' },
  { slug: 'balloon', title: "Balloon",
    author: "GrafxKid", sourceUrl: 'https://opengameart.org/content/various-creatures', license: 'CC0 1.0' },
  { slug: 'green-robot', title: "Green Robot",
    author: "GrafxKid", sourceUrl: 'https://opengameart.org/content/various-creatures', license: 'CC0 1.0' },
  { slug: 'blue-drop', title: "Blue Drop",
    author: "GrafxKid", sourceUrl: 'https://opengameart.org/content/various-creatures', license: 'CC0 1.0' },
  { slug: 'pink-cat', title: "Pink Cat",
    author: "GrafxKid", sourceUrl: 'https://opengameart.org/content/various-creatures', license: 'CC0 1.0' },
  { slug: 'ladybird', title: "Ladybird",
    author: "GrafxKid", sourceUrl: 'https://opengameart.org/content/various-creatures', license: 'CC0 1.0' },
  { slug: 'tv-robot', title: "TV Robot",
    author: "GrafxKid", sourceUrl: 'https://opengameart.org/content/various-creatures', license: 'CC0 1.0' },
  { slug: 'ghost', title: "Ghost",
    author: "GrafxKid", sourceUrl: 'https://opengameart.org/content/various-creatures', license: 'CC0 1.0' },
  { slug: 'red-apple', title: "Red Apple",
    author: "Sanglorian", sourceUrl: 'https://opengameart.org/content/64-16x16-food-sprites', license: 'CC0 1.0' },
  { slug: 'pineapple', title: "Pineapple",
    author: "Sanglorian", sourceUrl: 'https://opengameart.org/content/64-16x16-food-sprites', license: 'CC0 1.0' },
  { slug: 'beer-mug', title: "Beer Mug",
    author: "Sanglorian", sourceUrl: 'https://opengameart.org/content/64-16x16-food-sprites', license: 'CC0 1.0' },
  { slug: 'aubergine', title: "Aubergine",
    author: "Sanglorian", sourceUrl: 'https://opengameart.org/content/64-16x16-food-sprites', license: 'CC0 1.0' },
  { slug: 'strawberry', title: "Strawberry",
    author: "Sanglorian", sourceUrl: 'https://opengameart.org/content/64-16x16-food-sprites', license: 'CC0 1.0' },
  { slug: 'pretzel', title: "Pretzel",
    author: "Sanglorian", sourceUrl: 'https://opengameart.org/content/64-16x16-food-sprites', license: 'CC0 1.0' },
  { slug: 'watermelon', title: "Watermelon",
    author: "Sanglorian", sourceUrl: 'https://opengameart.org/content/64-16x16-food-sprites', license: 'CC0 1.0' },
  { slug: 'drumstick', title: "Drumstick",
    author: "Sanglorian", sourceUrl: 'https://opengameart.org/content/64-16x16-food-sprites', license: 'CC0 1.0' },
  { slug: 'shrimp', title: "Shrimp",
    author: "Sanglorian", sourceUrl: 'https://opengameart.org/content/64-16x16-food-sprites', license: 'CC0 1.0' },
  { slug: 'ramen-bowl', title: "Ramen Bowl",
    author: "maruki", sourceUrl: 'https://opengameart.org/content/16x16px-food-items', license: 'CC0 1.0' },
  { slug: 'fried-egg', title: "Fried Egg",
    author: "maruki", sourceUrl: 'https://opengameart.org/content/16x16px-food-items', license: 'CC0 1.0' },
  { slug: 'pizza-slice', title: "Pizza Slice",
    author: "maruki", sourceUrl: 'https://opengameart.org/content/16x16px-food-items', license: 'CC0 1.0' },
  { slug: 'maki-roll', title: "Maki Roll",
    author: "maruki", sourceUrl: 'https://opengameart.org/content/16x16px-food-items', license: 'CC0 1.0' },
  { slug: 'onigiri', title: "Onigiri",
    author: "maruki", sourceUrl: 'https://opengameart.org/content/16x16px-food-items', license: 'CC0 1.0' },
  { slug: 'donut', title: "Donut",
    author: "maruki", sourceUrl: 'https://opengameart.org/content/16x16px-food-items', license: 'CC0 1.0' },
  { slug: 'popsicle', title: "Popsicle",
    author: "maruki", sourceUrl: 'https://opengameart.org/content/16x16px-food-items', license: 'CC0 1.0' },
  { slug: 'hot-dog', title: "Hot Dog",
    author: "maruki", sourceUrl: 'https://opengameart.org/content/16x16px-food-items', license: 'CC0 1.0' },
  { slug: 'burger', title: "Burger",
    author: "maruki", sourceUrl: 'https://opengameart.org/content/16x16px-food-items', license: 'CC0 1.0' },
  { slug: 'clay-vase', title: "Clay Vase",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/rpg-item-set', license: 'CC0 1.0' },
  { slug: 'candelabra', title: "Candelabra",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/rpg-item-set', license: 'CC0 1.0' },
  { slug: 'kite-shield', title: "Kite Shield",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/rpg-item-set', license: 'CC0 1.0' },
  { slug: 'open-book', title: "Open Book",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/rpg-item-set', license: 'CC0 1.0' },
  { slug: 'flowering-plant', title: "Flowering Plant",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/rpg-item-set', license: 'CC0 1.0' },
  { slug: 'bread-loaf', title: "Bread Loaf",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/rpg-item-set', license: 'CC0 1.0' },
  { slug: 'mace', title: "Mace",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/rpg-item-set', license: 'CC0 1.0' },
  { slug: 'cabbage', title: "Cabbage",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/rpg-item-set', license: 'CC0 1.0' },
  { slug: 'salami', title: "Salami",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/rpg-item-set', license: 'CC0 1.0' },
  { slug: 'cucumber', title: "Cucumber",
    author: "Jetrel", sourceUrl: 'https://opengameart.org/content/rpg-item-set', license: 'CC0 1.0' },
  { slug: 'red-armchair', title: "Red Armchair",
    author: "NaRNeRZz", sourceUrl: 'https://opengameart.org/content/misc-household-items-and-more', license: 'CC0 1.0' },
  { slug: 'mantel-clock', title: "Mantel Clock",
    author: "NaRNeRZz", sourceUrl: 'https://opengameart.org/content/misc-household-items-and-more', license: 'CC0 1.0' },
  { slug: 'tulip-vase', title: "Tulip Vase",
    author: "NaRNeRZz", sourceUrl: 'https://opengameart.org/content/misc-household-items-and-more', license: 'CC0 1.0' },
  { slug: 'white-bed', title: "White Bed",
    author: "Jannax", sourceUrl: 'https://opengameart.org/content/home-objects', license: 'CC0 1.0' },
  { slug: 'blue-bed', title: "Blue Bed",
    author: "Jannax", sourceUrl: 'https://opengameart.org/content/home-objects', license: 'CC0 1.0' },
  { slug: 'table-lamp', title: "Table Lamp",
    author: "Reactorcore", sourceUrl: 'https://opengameart.org/content/lamps-lights-n-torches', license: 'CC0 1.0' },
  { slug: 'oil-lamp', title: "Oil Lamp",
    author: "Reactorcore", sourceUrl: 'https://opengameart.org/content/lamps-lights-n-torches', license: 'CC0 1.0' },
]

export const SHUFFLE_ALL = 'shuffle'

export function hasPicture(slug: string): boolean {
  return PICTURES.some((p) => p.slug === slug)
}

/** The slugs a selection plays, in the order it plays them.
 *
 *  Seeded, so a pinned seed reproduces the whole sequence — consistent with the
 *  seed field's documented job ("fixes the picture sequence") rather than an
 *  extension of it. An unknown selection degrades to everything rather than to
 *  nothing, so a link naming a sprite that has since been removed still plays. */
export function rotationOrder(selection: string, seed: number): string[] {
  if (hasPicture(selection)) return [selection]
  return shuffle(PICTURES.map((p) => p.slug), seed)
}

/** Fisher-Yates. A sort with a random comparator is NOT a uniform shuffle and is
 *  unstable across engines, either of which would break the determinism the seed
 *  contract promises. */
function shuffle(slugs: string[], seed: number): string[] {
  const out = slugs.slice()
  const rand = mulberry32(seed)
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1))
    ;[out[i], out[j]] = [out[j], out[i]]
  }
  return out
}

// Alphabetical by title, not sheet order: with ninety-odd entries a visitor hunting
// "Owl" should not have to scan a list ordered by which sheet it came from.
export const PICTURE_OPTIONS: SelectOption[] = [
  { value: SHUFFLE_ALL, label: 'Shuffle all' },
  ...PICTURES.map((p) => ({ value: p.slug, label: p.title }))
    .sort((a, b) => a.label.localeCompare(b.label)),
]
