import { defineDiversion, type PresetGroup } from '../../framework/types'
import { hyperbolicTilingSchema, type HyperbolicTilingConfig } from './schema'
import { generateTiling, type Tile } from './tiling'
import { renderTiling, buildBins, lightestColor, type TileBin } from './render'
import { tilingPresets, palettePresets } from './presets'

type HyperbolicTilingState = {
  cfg: HyperbolicTilingConfig
  w: number
  h: number
  tiles: Tile[]
  maxDepth: number
  bins: TileBin[] // precomputed per-(ring,parity) fill partition + colour — frame-invariant
  boundaryColor: string // precomputed lightestColor(cfg.colors) — frame-invariant
  time: number // seconds, accumulated — feeds the Möbius drift
}

function buildTiles(cfg: HyperbolicTilingConfig): { tiles: Tile[]; maxDepth: number } {
  const tiles = generateTiling(cfg.p, cfg.q, cfg.depth)
  let maxDepth = 0
  for (const t of tiles) if (t.depth > maxDepth) maxDepth = t.depth
  return { tiles, maxDepth }
}

const presets: PresetGroup<HyperbolicTilingConfig>[] = [
  { label: 'Tiling', options: tilingPresets },
  { label: 'Palette', options: palettePresets },
]

const hyperbolicTiling = defineDiversion<typeof hyperbolicTilingSchema, HyperbolicTilingState, '2d'>({
  id: 'hyperbolic-tiling',
  title: 'Hyperbolic Tiling',
  description: 'An Escher-style Circle Limit tessellation of the hyperbolic plane, generated by a reflection group of geodesic arcs and drawn in the Poincaré disk. The whole tiling drifts in a slow hyperbolic translation that carries tiles from the centre out toward the ever-more-crowded boundary, forever.',
  kind: '2d',
  schema: hyperbolicTilingSchema,
  presets,

  setup(_ctx, config, size) {
    const { tiles, maxDepth } = buildTiles(config)
    const bins = buildBins(tiles, maxDepth, config.colors)
    const boundaryColor = lightestColor(config.colors)
    return { cfg: config, w: size.width, h: size.height, tiles, maxDepth, bins, boundaryColor, time: 0 }
  },

  frame(state, ctx, _t, dt) {
    state.time += dt / 1000
    renderTiling(ctx, state.cfg, state.w, state.h, state.tiles, state.bins, state.boundaryColor, state.time)
  },

  resize(state, size) {
    // The tiling lives in the unit disk (viewport-independent) — a resize just
    // changes w/h so render() rescales to fit; never regenerate the geometry.
    state.w = size.width
    state.h = size.height
  },

  update(state, config) {
    // Bins (the ring/parity fill partition) depend on the tiling geometry AND the
    // colour ramp — rebuild whenever either changes, but never per-frame.
    if (config.p !== state.cfg.p || config.q !== state.cfg.q || config.depth !== state.cfg.depth) {
      const { tiles, maxDepth } = buildTiles(config)
      state.tiles = tiles
      state.maxDepth = maxDepth
      state.bins = buildBins(state.tiles, state.maxDepth, config.colors)
      state.boundaryColor = lightestColor(config.colors)
    } else if (config.colors !== state.cfg.colors) {
      state.bins = buildBins(state.tiles, state.maxDepth, config.colors)
      state.boundaryColor = lightestColor(config.colors)
    }
    state.cfg = config
    return true // style / lineWidth / driftSpeed all read live in render
  },
})

export default hyperbolicTiling
