import type { DiversionMeta } from '../../framework/types'

/** Gallery card + routing identity. Split from index.ts so the registry can
 *  eager-glob every diversion's identity while lazy-importing its code (#288). */
export const meta = {
  id: 'hyperbolic-tiling',
  title: 'Hyperbolic Tiling',
  description: 'An Escher-style Circle Limit tessellation of the hyperbolic plane, generated by a reflection group of geodesic arcs and drawn in the Poincaré disk. The whole tiling drifts in a slow hyperbolic translation that carries tiles from the centre out toward the ever-more-crowded boundary, forever.',
  kind: '2d',
} as const satisfies DiversionMeta
