// Poincaré-disk geometry for a regular {p,q} hyperbolic tiling — pure & unit
// tested, no canvas/ctx here (see render.ts for drawing). Everything lives in
// the open unit disk; the boundary circle |z|=1 is the ideal (infinite) rim.
//
// Approach: a regular {p,q} tiling is generated by the reflection group of its
// central polygon — repeatedly reflecting tiles across their own edges (each
// edge lies on a geodesic: a circular arc orthogonal to the unit circle, or a
// diameter through the origin in the degenerate case) breadth-first, deduping
// by centroid so each tile is emitted once. This mirrors how every hand-drawn
// "Circle Limit"-style generator works (Escher used compass-and-straightedge
// inversions by hand for exactly this reason).

export type Pt = [number, number]

export type Tile = {
  vertices: Pt[]
  depth: number // BFS ring index: 0 = central polygon, 1 = first ring, …
}

export type Circle = { c: Pt; r: number }

const EPS = 1e-9

/** (p−2)(q−2) > 4 is the hyperbolic condition for a regular {p,q} tiling — the
 *  flat cases (=4: {3,6},{4,4},{6,3}) and spherical cases (<4) don't apply. */
export function isValidPQ(p: number, q: number): boolean {
  return Number.isInteger(p) && Number.isInteger(q) && p >= 3 && q >= 3 && (p - 2) * (q - 2) > 4
}

/** Snap an arbitrary (possibly invalid) {p,q} to the nearest valid hyperbolic
 *  pair: round + clamp to ≥3, then grow q (more tiles per vertex almost always
 *  restores validity fastest), then p, then fall back to the always-valid
 *  {7,3}. Never throws, never returns an invalid pair. */
export function resolvePQ(p: number, q: number): [number, number] {
  const pp = Math.max(3, Math.round(Number.isFinite(p) ? p : 7))
  const qq = Math.max(3, Math.round(Number.isFinite(q) ? q : 3))
  if (isValidPQ(pp, qq)) return [pp, qq]
  for (let d = 1; d <= 24; d++) {
    if (isValidPQ(pp, qq + d)) return [pp, qq + d]
  }
  for (let d = 1; d <= 24; d++) {
    if (isValidPQ(pp + d, qq)) return [pp + d, qq]
  }
  return [7, 3]
}

/** Euclidean (Poincaré-disk) radius of the central {p,q} polygon's vertices.
 *  Derived from the Schwarz right triangle (centre, vertex, edge-midpoint)
 *  with angles π/p (at centre), π/q (half the vertex angle) and π/2: the
 *  hyperbolic-right-triangle identity cosh(c) = cot(π/p)·cot(π/q) gives the
 *  centre→vertex hyperbolic distance c, and r = tanh(c/2) converts it to the
 *  disk-model Euclidean radius. */
export function centerRadius(p: number, q: number): number {
  const cotP = 1 / Math.tan(Math.PI / p)
  const cotQ = 1 / Math.tan(Math.PI / q)
  const coshC = Math.max(1 + 1e-9, cotP * cotQ) // guard: clamp away from the invalid (<1) region
  const c = Math.acosh(coshC)
  return Math.tanh(c / 2)
}

/** The p vertices of the central regular polygon, evenly spaced on its circle. */
export function centralPolygon(p: number, q: number): Pt[] {
  const r0 = centerRadius(p, q)
  const verts: Pt[] = []
  for (let i = 0; i < p; i++) {
    const a = (i / p) * Math.PI * 2 - Math.PI / 2 // first vertex points "up"
    verts.push([r0 * Math.cos(a), r0 * Math.sin(a)])
  }
  return verts
}

/** The circle through a and b that is orthogonal to the unit circle — i.e. the
 *  hyperbolic geodesic through a and b, extended to a full Euclidean circle.
 *  Orthogonality to |z|=1 requires |c|² = r² + 1; combined with the circle
 *  passing through a and b this is a 2×2 linear system in c. Returns null when
 *  a, b and the origin are (numerically) collinear — the geodesic degenerates
 *  to a straight diameter, which has no finite orthogonal-circle radius. */
export function geodesicCircle(a: Pt, b: Pt): Circle | null {
  const [ax, ay] = a
  const [bx, by] = b
  const D = ax * by - ay * bx
  if (Math.abs(D) < EPS) return null
  const ea = (ax * ax + ay * ay + 1) / 2
  const eb = (bx * bx + by * by + 1) / 2
  const cx = (ea * by - eb * ay) / D
  const cy = (ax * eb - bx * ea) / D
  const r2 = cx * cx + cy * cy - 1
  return { c: [cx, cy], r: Math.sqrt(Math.max(0, r2)) }
}

/** Circle inversion of p across circle (c, r) — an involution (inverting
 *  twice returns p). This IS the hyperbolic reflection across the geodesic
 *  that circle sits on. */
export function invert(p: Pt, c: Pt, r: number): Pt {
  const dx = p[0] - c[0]
  const dy = p[1] - c[1]
  const d2 = dx * dx + dy * dy
  if (d2 < EPS) return p // p sits at the circle's own centre — degenerate, leave it
  const k = (r * r) / d2
  return [c[0] + dx * k, c[1] + dy * k]
}

/** Euclidean reflection of p across the line through the origin at angle
 *  theta — an involution. This is the degenerate (diameter) geodesic case. */
export function reflectLine(p: Pt, theta: number): Pt {
  const c2 = Math.cos(2 * theta)
  const s2 = Math.sin(2 * theta)
  return [p[0] * c2 + p[1] * s2, p[0] * s2 - p[1] * c2]
}

/** Reflect p across the hyperbolic geodesic through a and b — an involution
 *  in both branches (circle inversion, or the degenerate line reflection). */
export function reflectAcrossGeodesic(p: Pt, a: Pt, b: Pt): Pt {
  const g = geodesicCircle(a, b)
  if (!g) return reflectLine(p, Math.atan2(a[1], a[0]))
  return invert(p, g.c, g.r)
}

/** Which of the two sweep directions from a to b around circle (c,r) stays
 *  inside the unit disk. A geodesic circle crosses the unit circle at two
 *  points, splitting it into an inside arc and an outside arc; since a and b
 *  both lie strictly inside the disk, exactly one direction between them is
 *  the inside one. Sampled at the candidate arc's own midpoint so it's robust
 *  to either point being the "later" one angularly. */
export function arcSpan(a: Pt, b: Pt, c: Pt, r: number): { start: number; end: number; ccw: boolean } {
  const start = Math.atan2(a[1] - c[1], a[0] - c[0])
  const end = Math.atan2(b[1] - c[1], b[0] - c[0])
  let delta = end - start
  while (delta <= -Math.PI) delta += Math.PI * 2
  while (delta > Math.PI) delta -= Math.PI * 2
  const mid = start + delta / 2
  const mx = c[0] + r * Math.cos(mid)
  const my = c[1] + r * Math.sin(mid)
  const shortWayInside = mx * mx + my * my <= 1
  const ccw = shortWayInside ? delta < 0 : !(delta < 0)
  return { start, end, ccw }
}

const MAX_TILES = 2000 // hard cap: keeps every frame cheap no matter how fast {p,q} branches

function tileKey(vs: Pt[]): string {
  let sx = 0, sy = 0
  for (const [x, y] of vs) { sx += x; sy += y }
  return `${(sx / vs.length).toFixed(6)},${(sy / vs.length).toFixed(6)}`
}

/** Breadth-first reflection-group tiling: start from the central {p,q}
 *  polygon, then repeatedly reflect every tile across each of its own edges,
 *  deduping by centroid so each tile in the orbit is emitted exactly once.
 *  `depth` rings are grown (ring 0 = the central tile); the walk also stops
 *  early once MAX_TILES is hit, whichever comes first — so a runaway {p,q}
 *  (small q, e.g. {3,7}) degrades to a truncated-but-still-valid tiling
 *  instead of hanging or blowing the frame budget. */
export function generateTiling(p: number, q: number, depth: number): Tile[] {
  const [pp, qq] = resolvePQ(p, q)
  const base = centralPolygon(pp, qq)
  const root: Tile = { vertices: base, depth: 0 }
  const tiles: Tile[] = [root]
  const visited = new Set<string>([tileKey(base)])
  const queue: Tile[] = [root]
  let head = 0
  while (head < queue.length && tiles.length < MAX_TILES) {
    const cur = queue[head++]
    if (cur.depth >= depth - 1) continue // don't expand past the requested ring count
    for (let e = 0; e < pp; e++) {
      const a = cur.vertices[e]
      const b = cur.vertices[(e + 1) % pp]
      const reflected = cur.vertices.map((v) => reflectAcrossGeodesic(v, a, b))
      const key = tileKey(reflected)
      if (visited.has(key)) continue
      visited.add(key)
      const tile: Tile = { vertices: reflected, depth: cur.depth + 1 }
      tiles.push(tile)
      queue.push(tile)
      if (tiles.length >= MAX_TILES) break
    }
  }
  return tiles
}

// ─── Animation: a slow Möbius drift so tiles perpetually flow toward the rim ──

const RAPIDITY_RATE = 0.15 // 1/s — how fast the translation's magnitude ramps up
const SWIRL_RATE = 0.05 // rad/s — how fast the translation's axis orbits (never stops)
const MAX_MAGNITUDE = 0.88 // absolute ceiling: stays comfortably short of the rim (|a|<1)
const DRIFT_MARGIN = 0.2 // drift as a fraction of the patch's own hyperbolic radius (see driftCap)

/** The largest drift magnitude that keeps the disk centre covered for THIS finite
 *  patch. A {p,q} patch is a solid hyperbolic ball that only tessellates out to its
 *  own outer radius R_out (Euclidean) — i.e. hyperbolic radius ρ = 2·atanh(R_out).
 *  A disk-automorphism translation by rapidity δ moves the whole ball off-origin, so
 *  once δ ≥ ρ the origin itself falls outside the patch and ~half the disk goes bare
 *  (issue #261). Capping the translation at a fraction of ρ keeps the origin — and
 *  most of the disk — always covered, while small/sparse patches (small ρ) drift
 *  proportionally less than deep ones. |a| = tanh(δ/2) = tanh(DRIFT_MARGIN·atanh(R_out)). */
export function driftCap(tiles: Tile[]): number {
  let rMax = 0
  for (const t of tiles) {
    for (const [x, y] of t.vertices) {
      const r = Math.sqrt(x * x + y * y)
      if (r > rMax) rMax = r
    }
  }
  rMax = Math.min(rMax, 0.9995) // atanh guard: a near-rim vertex must not blow the cap up to 1
  return Math.min(MAX_MAGNITUDE, Math.tanh(DRIFT_MARGIN * Math.atanh(rMax)))
}

/** The disk-automorphism translation parameter `a` (as a point) at time t: its
 *  magnitude eases up toward `maxMag` (a hyperbolic "constant velocity" translation —
 *  translations along a fixed axis commute, so accumulated rapidity is linear in t
 *  and the Euclidean magnitude is tanh of that) while its direction keeps slowly
 *  orbiting — so the flow never settles into a static picture even once the magnitude
 *  has saturated. `maxMag` is the per-patch `driftCap` so the disk never empties
 *  (defaults to the absolute ceiling for callers that don't have the patch). */
export function moebiusOffset(time: number, driftSpeed: number, maxMag: number = MAX_MAGNITUDE): Pt {
  if (driftSpeed <= 0) return [0, 0]
  const mag = maxMag * Math.tanh(driftSpeed * RAPIDITY_RATE * time)
  const phase = driftSpeed * SWIRL_RATE * time
  return [mag * Math.cos(phase), mag * Math.sin(phase)]
}

/** Apply the disk automorphism w = (z+a)/(1+conj(a)·z) (z, a as complex
 *  numbers via their (x,y) components) — the standard Möbius isometry of the
 *  Poincaré disk. Maps the whole disk (and every geodesic in it) to itself. */
export function applyMoebius(p: Pt, a: Pt): Pt {
  const [x, y] = p
  const [ax, ay] = a
  const nr = x + ax
  const ni = y + ay
  const dr = 1 + ax * x + ay * y
  const di = ax * y - ay * x
  const denom = dr * dr + di * di
  if (denom < EPS) return p
  return [(nr * dr + ni * di) / denom, (ni * dr - nr * di) / denom]
}
